apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cred-config
data:
  config: |
    [default]
    region = us-east-1
  syncs3.sh: |
    export AWS_ACCESS_KEY_ID=****************
    export AWS_SECRET_ACCESS_KEY=****************
    export AWS_CONFIG_FILE="/root/.aws/config"
    aws s3 sync /var/log/nginx s3://vinaykumar123s3

